spring:
  application:
    name: mall-user

  # ==================== 关键：使用 spring.config.import ====================
  config:
    import: optional:nacos:mall-user.yaml?refreshEnabled=true

  cloud:
    nacos:
      server-addr: 192.168.1.102:8848
      config:
        server-addr: ${spring.cloud.nacos.server-addr}
        group: DEFAULT_GROUP          # 可选，默认就是 DEFAULT_GROUP
        namespace: public
        file-extension: yaml
        # username: nacos
        # password: nacos

      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}